const stretchingData = [
  { id: 1, name: '스트레칭', image: '/video/IMG_2879.MOV' },
  { id: 2, name: '스트레칭', image: '/video/IMG_2880.MOV' },
  { id: 3, name: '스트레칭', image: '/video/IMG_2882.MOV' },
  { id: 4, name: '스트레칭', image: '/video/IMG_2883.MOV' },
  { id: 5, name: '스트레칭', image: '/video/IMG_2884.MOV' },
  { id: 6, name: '스트레칭', image: '/video/IMG_2885.MOV' },
  { id: 7, name: '스트레칭', image: '/video/IMG_2886.MOV' },
  { id: 8, name: '스트레칭', image: '/video/IMG_2887.MOV' },
  { id: 9, name: '스트레칭', image: '/video/IMG_2888.MOV' },
  { id: 10, name: '스트레칭', image: '/video/IMG_2890.MOV' },
  { id: 11, name: '스트레칭', image: '/video/IMG_2891.MOV' },
  { id: 12, name: '스트레칭', image: '/video/IMG_2892.MOV' },
  { id: 13, name: '스트레칭', image: '/video/IMG_2893.MOV' },
  { id: 14, name: '스트레칭', image: '/video/IMG_2894.MOV' },
  { id: 15, name: '스트레칭', image: '/video/IMG_2895.MOV' },
  { id: 16, name: '스트레칭', image: '/video/IMG_2896.MOV' },
  { id: 17, name: '스트레칭', image: '/video/IMG_2898.MOV' },
  { id: 18, name: '스트레칭', image: '/video/IMG_2899.MOV' },
  { id: 19, name: '스트레칭', image: '/video/IMG_2900.MOV' },
  { id: 20, name: '스트레칭', image: '/video/IMG_2901.MOV' },
  { id: 21, name: '스트레칭', image: '/video/IMG_2903.MOV' },
  { id: 22, name: '스트레칭', image: '/video/IMG_2906.MOV' },
  { id: 23, name: '스트레칭', image: '/video/IMG_2907.MOV' },
  { id: 24, name: '스트레칭', image: '/video/IMG_2908.MOV' },
  { id: 25, name: '스트레칭', image: '/video/IMG_2909.MOV' },
  { id: 26, name: '스트레칭', image: '/video/IMG_2910.MOV' },
  { id: 27, name: '스트레칭', image: '/video/IMG_2911.MOV' },
  { id: 28, name: '스트레칭', image: '/video/IMG_2912.MOV' },
  { id: 29, name: '스트레칭', image: '/video/IMG_2913.MOV' },
  { id: 30, name: '스트레칭', image: '/video/IMG_2914.MOV' },
  { id: 31, name: '스트레칭', image: '/video/IMG_2915.MOV' },
  { id: 32, name: '스트레칭', image: '/video/IMG_2917.MOV' },
  { id: 33, name: '스트레칭', image: '/video/IMG_2918.MOV' },
];

export default stretchingData;
